### PR TITLE
fix problem of email address in brackets

### LINKED ISSUE #34: email address parsing wrong wrt brackets
when right clicking an email address in brackets, the brackets are copied as if they're part of the email address:

Screenshot 2023-05-27 at 00 31 21

this copies `(me@foobar.de)` instead of `me@foobar.de` to the clipboard (if you look closely, the brackets are also underlined wrongly)

EDIT: just noticed: if you tap, you'll also start a chat with the (wrong) email address `(me@foobar.de)`:

Screenshot 2023-05-27 at 00 33 55

### PR DESCRIPTION
**Pull request by farooqkz**
Fixes #34

### CODE REVIEW

**Review by Simon-Laux — APPROVED** [review]

**Comment by Simon-Laux** [comment]
changelog entry would be nice, then we can merge it.
wikipedia says that `()` is allowed sometimes: 
> Comments are allowed with parentheses at either end of the local-part; e.g., john.smith(comment)@example.com and (comment)john.smith@example.com are both equivalent to john.smith@example.com.

But I'm not sure if Deltachat even supports that, so let's not bother for now, you can always just copy paste by hand.

**Comment by farooqkz** [comment]
@Simon-Laux Done

**Review by Simon-Laux — APPROVED** [review]

**Comment by Simon-Laux** [comment]
rustfmt complains

**Comment by farooqkz** [comment]
> rustfmt complains

I've bribed him to not complain. You can merge it now :)

**Pull request merged**
