### PR TITLE
fix ipv6 mistaken is punycode

### LINKED ISSUE #35: ipv6 address is mistaken for containing unicode / puny-code-domains
input:
```
http://[2001:0db8:85a3:08d3::0370:7344]:8080/
```
expected output:
```json
[
    {
        "t": "Link",
        "c": {
            "destination": {
                "target": "http://[2001:0db8:85a3:08d3::0370:7344]:8080/",
                "hostname": "[2001:0db8:85a3:08d3::0370:7344]",
                "punycode": null
            }
        }
    }
]
```
actual output
```json
[
    {
        "t": "Link",
        "c": {
            "destination": {
                "target": "http://[2001:0db8:85a3:08d3::0370:7344]:8080/",
                "hostname": "[2001:0db8:85a3:08d3::0370:7344]",
                "punycode": {
                    "original_hostname": "[2001:0db8:85a3:08d3::0370:7344]",
                    "ascii_hostname": "xn--[2001:0db8:85a3:08d3::0370:7344]-",
                    "punycode_encoded_url": "http://xn--[2001:0db8:85a3:08d3::0370:7344]-:8080/"
                }
            }
        }
    }
]
```

### PR DESCRIPTION
**Pull request by farooqkz**
This fixes #35

### CODE REVIEW

**Review by Simon-Laux — CHANGES_REQUESTED** [review]
please add tests and a changelog entry

**Comment by farooqkz** [comment]
@Simon-Laux I have added the tests but Rust is complaining the properties of `LinkDestination` are private. Am I doing it wrong?

**Comment by farooqkz** [comment]
> I think I added a special way to generate those destinations for the tests, if you can not find it in the code you could either make a new function that is only compiled for tests, that generates it (cfg test) or make the link destination struct public.

`link_destination_for_testing` is used. But this uses `LinkDestination::parse` which the tests are written for :/

I can write that function but still I'll have to make entries of `LinkDestination` public.

**Comment by Simon-Laux** [comment]
make it public for now, if it's easier, having tests is more important than a "super pretty" api

**Comment by farooqkz** [comment]
@Simon-Laux Ready to merge I guess

**Review by Simon-Laux — APPROVED** [review]

**Pull request merged**
